project:
  type: book
  output-dir: docs

book:
  title: "Estadísticas e Indicadores en la Gestión Pública"
  subtitle: "Aproximación Teórica y Práctica"
  author: 
  - name: David Santiago Hernández Ardila
    affiliation: 
      - Oficina Nacional de Estadística
      - Dirección Nacional de Planeación y Estadística
      - Universidad Nacional de Colombia
  - name: Alberto Rodríguez Rodríguez
    affiliation: 
     - Oficina Nacional de Estadística
     - Dirección Nacional de Planeación y Estadística
     - Universidad Nacional de Colombia
  google-analytics: "G-GX6R5Z755F"
  cover-image: Imagenes/portada.jpg
  repo-url: https://github.com/estadisticaun/L_Conceptual1
  repo-branch: master
  repo-actions: [edit]
  sharing: [twitter, facebook, linkedin]
  date:  01/12/2023
  date-format: "MM-D-YYYY"
  reader-mode: true
  page-footer:
    left: |
      <a href="https://estadisticas.unal.edu.co/home/">Oficina Nacional de Estadística</a><br><a href="https://planeacion.unal.edu.co/home/">Dirección Nacional de Planeación y Estadística</a><br>Universidad Nacional de Colombia. 
    right: |
      Este libro fue construido con <a href="https://quarto.org/">Quarto</a>.
    center: |
      Estadísticas e Indicadores
    background: "#ECEFF1"
    foreground: "#37474F"
    border: true
  chapters:
    - index.qmd
    - presentacion.qmd
    - introduccion.qmd
    - Cap_I.qmd
    - Cap_II.qmd
    - Cap_III.qmd
    - Cap_IV.qmd
    - conclusiones.qmd
    - references.qmd
  sidebar:
    title: " "
    logo: 'Imagenes/portada.jpg'
    
bibliography: references.bib

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: style.css
    
editor: visual

