# Información y gestión pública

El presente capítulo explora el concepto de información y su relación con la gestión pública. Para ello, en primer lugar, se abordarán los problemas conceptuales de la información, discutiendo la importancia del concepto en el contexto histórico actual, sus problemas teóricos, definiciones y características. En segundo lugar, se analiza la gestión pública como una unidad temática aislada con el fin de brindar al lector un panorama general de sus implicaciones. Finalmente, el objetivo del capítulo es ayudar al lector a entender la relación entre información y gestión pública; comprender el papel especial que tiene la información cuantitativa en dicha relación y, por último, alertar acerca de los retos y las exigencias éticas involucradas en el manejo y uso de la información dentro del marco de la gestión pública.

## Información

La palabra “información” resulta ser un término bastante habitual en las interacciones sociales. Es una de esas palabras que se emplea sin mayor complicación en diferentes contextos. Cuando se dice que “hay que estar informados” o que “debemos cuidar nuestra información personal”, no se sabe lo suficiente al respecto de lo que se está entendiendo por información; simplemente, se tiene la sensación de comprender lo que se dice.

No es casualidad que el término en cuestión resulte tan habitual, parece ser que el momento actual es el momento de la información. Tanto los avances en materia de telecomunicaciones y computación como la aparición del universo digital han condicionado en gran medida los modos en que se interactúa con el mundo y con los demás. Lo anterior al punto en el que la mayoría de las experiencias humanas se ven permeadas, de una u otra forma, por el consumo y la transmisión de información. De hecho, autores como [@Masuda], [@Castells] o [@Moore] se refieren a una “sociedad de la información”, esto es, una sociedad donde los modos en que se produce, se consume y se emplea la información resultan de importancia notable para el devenir social [^cap_i-1].

[^cap_i-1]: Por supuesto, esta forma de clasificar o describir las sociedades no es del todo universal, pues existen comunidades excluidas o ajenas al “Estado moderno” y a las prácticas sociales globales. Sin embargo, las sociedades de la información parecen ser el camino al que tienden la mayoría de las comunidades.

La importancia concedida al tema de la información en la época actual se puede notar en eventos como la Cumbre Mundial sobre la Sociedad de la Información, llevada a cabo en 2003 con delegados de 175 países, donde se trataron los temas de acceso a la información y de la “gobernanza de internet”.

La Cumbre Mundial sobre la Sociedad de la Información tuvo una segunda fase en 2005. Allí, además del tema del acceso a la información, se trató la cuestión del “dilema digital”. Tal cuestión tiene que ver con la opinión bastante extendida de que fenómenos como la sociedad de la información, la era digital, el internet y otros similares pueden fomentar algunas problemáticas que vale la pena considerar.

Por ejemplo, uno de los elementos centrales del “dilema” está asociado a la *cantidad* de contenidos que se producen y que se consumen. Todos los días se transmiten y recepcionan más datos de los que cualquier ser humano por sí mismo podría procesar en toda su vida. De hecho, según un reporte del gigante del contenido audiovisual YouTube, en dicha plataforma se veían para 2017 más de mil millones de horas de video por día, es decir, más de cien mil años de reproducción continua [@Goodrow]. Con tanta información resulta bastante difícil organizar, direccionar y controlar el contenido que se presenta. A causa de esta “sobrecarga” de información y de las dificultades para gestionarla, se presentan problemáticas como las *fake news*, la posverdad, la pérdida de credibilidad; en una palabra, la *desinformación*.

La cantidad no es el único problema asociado a la era digital, en general, y a la información, en particular. También es importante considerar la cuestión de la distribución. Pongamos en cuestión el caso de las redes sociales. Los algoritmos de estas redes muestran contenidos “cercanos” a las creencias de los consumidores. Así, el contenido que consume una persona con unos intereses particulares puede ser diametralmente opuesto al de otra persona con otros intereses. En principio esto no parece ser problemático. Sin embargo, en la actualidad, las redes sociales constituyen parte importante de la interpretación que se hace del mundo y de los modos en que las personas se relacionan con él. De manera que el sentido de realidad ya no es compartido, cada persona accede a una “verdad” distinta programada en su celular, o lo que [@Pariser] denomina “burbuja filtrada”. Esto lleva, entre otras, a la polarización y la falta de empatía.

Otro elemento que vale la pena considerar tiene que ver con *los modos y los propósitos* para obtener información. Un buen ejemplo podría ser lo sucedido en 2018 con Facebook y Cambridge Analytics. De acuerdo con [@Greenfield], una asociación privada, Cambridge Analytics, pudo acceder a información personal de miles de usuarios en Facebook y, con base en dicha información, manipular las elecciones presidenciales de los Estados Unidos. Esta situación pone de manifiesto cuestiones como a quién le pertenece la información, qué se puede hacer y qué no hacer con ella, cuál es el límite entre lo privado y lo público de la información, entre otros asuntos cuestionables.

Como se ha visto, la información emerge como un tema de relevancia contemporánea que convoca diversas problemáticas a su alrededor. Ahora bien, desde la perspectiva del presente libro, la información se presenta como un elemento necesario para la construcción de cifras estadísticas sobre las cuales es posible la gestión de los Estados y sus instituciones. De modo que en lo que sigue del presente capítulo se discute la noción de información, explorando su comprensión y evolución histórica, mientras se tejen conexiones entre información y gestión pública.

### Definición de información

El concepto de información es problemático. A pesar de su cotidianidad y de su presencia en nuestras actividades más básicas, no es tan sencillo precisar sus particularidades y distinguirlo, por ejemplo, de otros conceptos como conocimiento, saber, dato, noticia o, incluso, aprendizaje. De hecho, [@Buckland] resalta que es bastante irónico pensar en la información como algo asociado a la reducción de la ignorancia y de la incertidumbre y, sin embargo, se use de manera tan amplia y en contextos tan diversos.

#### Etimología de la información

Como es costumbre, cuando se quiere precisar el significado de alguna palabra, se suele recurrir a su etimología. “Información” viene del latín *informatio*, que es la forma nominal del verbo *informare*, que quiere decir dar forma. Resulta importante resaltar que tal término implica una cierta acción o evento, no es estático; no es solo una forma, sino *dar* forma. Precisamente, el sufijo ---*tio*, de *informa---tio*, denota acción o efecto. Por su parte, “dar forma” tiene que ver con definir, limitar, organizar. La forma tiene siempre una estructura. De hecho, el radical *forma* se encuentra también en *formalis*, formal. Con respecto al prefijo *in*--- se relaciona con la raíz indoeuropea *en*, que designa un cierto tránsito hacia dentro, justamente este prefijo se encuentra en *internus*, interno. Así, se puede decir que el término mencionado refiere a una cierta estructura ---o forma--- interna (*in---forma*) que implica la acción, el movimiento, el suceso (---*tio*).

#### Enfoque pragmático

Con todo, esta aproximación al concepto es, aún, bastante general. Otra buena forma de continuar abordando el sentido que se le asigna al término “información” es atender a sus contextos de uso. Como menciona [@Buckland pp.351], “frente a la variedad de significados \[...\] al menos podemos adoptar un enfoque pragmático”.

De este modo, [@Buckland] distingue tres grandes usos del término en las conversaciones habituales, a saber: información como proceso, información como conocimiento e información como cosa. En el primero, *información como proceso*, se resalta el carácter activo del concepto: la información como el acto de informar. Esta concepción involucra un *proceso* de carácter comunicativo donde el elemento central no es lo comunicado sino, justamente, el acto de comunicar, de informar. En el segundo, sobre la *información como conocimiento*, se destaca un evento posterior al acto de informar. Es decir, el foco ya no está en el proceso comunicativo, sino en su consecuencia: cuando alguien es informado sobre algún aspecto, hay algo que percibe y que, de alguna manera, cambia lo que sabe al respecto de un tema en concreto. Para Buckland estos dos usos de la palabra (como proceso y como conocimiento) se caracterizan por su inteligibilidad: “si se puede tocar o medir de manera directa, no es conocimiento \[ni proceso\], sino algo físico” [@Buckland pp.352]. Así, el tercer uso del término, el de *información como cosa*, hace referencia a la información como una entidad física que puede transmitir o comunicar algo.

Hasta ahora se ha mostrado que Buckland expone tres usos posibles que se hacen del término *información*: como proceso, como conocimiento y como cosa. Resulta importante destacar que es posible establecer una distinción entre los términos que subyacen a los usos mencionados. Por ejemplo, el informático danés [@Ingwersen] [^cap_i-2] establece una precisión clara que distingue datos, información y conocimiento. Para este autor, los datos se definen como información en potencia, es decir, información como cosa, que solo es realmente información cuando es percibida por un receptor. Así, para Ingwersen, la diferencia entre el dato (información potencial, que no ha sido percibida) y la información propiamente dicha tiene que ver con la transformación por parte del receptor de los datos a través de sus estructuras de conocimiento. Con respecto al conocimiento, Ingwersen menciona que ocurre cuando la información, es decir, los datos percibidos, modifican la estructura de conocimiento del receptor.

[^cap_i-2]: Hace parte de un enfoque subjetivo y considera que la información (como dato percibido) solamente se puede dar entre humanos.

Ahora bien, las definiciones de [@Buckland] e [@Ingwersen] no son opuestas ni contradictorias, sino que resultan complementarias. Buckland denomina *información como cosa* a lo que Ingwersen llama *dato*; información como proceso a lo que en Ingwersen es información en sentido estricto; y, finalmente, *información como conocimiento* a lo que, en términos de Ingwersen, es simplemente, *conocimiento*.

Con todo, abordar el concepto de información desde una perspectiva pragmática involucra, por lo menos, tres elementos: un objeto que se puede administrar (p. ej. almacenar, medir, distribuir, copiar) y que vendría siendo *información como cosa* para Buckland o *dato* para Ingwersen; un proceso interactivo donde se comunica algo, *información como proceso* para Buckland o *información*, en sentido estricto, para Ingwersen y, por último, un aspecto conceptual, donde se sabe, se cree, se conoce o se opina algo, es decir, información como conocimiento [^cap_i-3] para Buckland o conocimiento para Ingwersen [^cap_i-4].

[^cap_i-3]: Como se sabe, desde la tradición filosófica de la antigua Grecia se establece una distinción categórica entre conocimiento (*episteme*), por un lado, y opinión o creencia (*doxa*), por el otro. En esta ocasión, sin embargo, con *información como conocimiento* se hace referencia a un aspecto conceptual en sentido amplio.

[^cap_i-4]: Sin embargo, acá no se agotan los problemas. Es posible preguntarse si la información como proceso, en tanto situacional e intencional, puede darse también en animales u objetos. De manera similar, el conocimiento, en tanto representación conceptual, remite a la pregunta por lo cognitivo y pone en cuestión asuntos actuales como el *machine learning*. No obstante, estos elementos no hacen parte propiamente de un enfoque pragmático de la información.

[@Buckland] argumenta que el ámbito académico se ha concentrado, sobre todo, en la información como proceso y como conocimiento, no así en la información como cosa. Sin embargo, para el autor, la información como cosa posee una importancia notable en la medida en que los sistemas de información, encargados de procesar, preservar, extraer o predecir información, solo pueden operar con la información como cosa.

En este punto, cabe destacar que el presente libro hace parte de una indagación estadística y la estadística involucra, justamente, una serie de técnicas de descripción, recopilación, registro y cálculo que se aplican al dato, a las cifras, a los documentos, en una palabra, a la información como cosa. De modo que tal noción de la información, en tanto información que es susceptible de ser procesada, resulta crucial para la estadística y, por lo tanto, para este libro. Desde este punto de vista, en adelante el texto se concentra en la concepción de *información como cosa*.

La *información como cosa* hace referencia, justamente, a las cosas que pueden ser informativas, como, por ejemplo, un libro, una película o una base de datos. Pero ¿qué cosas pueden ser informativas? o, mejor, ¿qué cosas no lo son? Pues bien, para Buckland la información como cosa se caracteriza por ser prueba o evidencia de algo. Así, una cosa puede ser informativa en la medida en que sirva como evidencia de algo en alguna situación. De manera que, respondiendo a la pregunta de qué cosas no pueden ser informativas, el autor afirma que prácticamente cualquier cosa puede ser considerada información: “llegamos a la conclusión de que somos incapaces de decir con confianza que algo no podría ser información” [@Buckland pp.356].

Aun así, Buckland establece cuatro tipos de información como cosa: los datos, los documentos, los objetos y los eventos. A continuación, se aborda cada uno de ellos.

##### Dato (o data)

La palabra “dato” viene del latín *datum* que deriva, a su vez, del verbo dare y se refiere a “lo que nos es dado”. Buckland toma esta concepción etimológica para argumentar que los datos tienen que ver con la “información como cosa que se ha procesado de alguna manera para su uso” [@Buckland pp. 353]. Dicho de otro modo, en la medida en que los datos tienen que ver con algo que “es dado” implican un determinado proceso y ahí radica la asociación entre algo que es *dado* y algo *procesado* para ser usado. De otro modo, el autor resalta que, con frecuencia, los datos se asocian a registros que se almacenan en una computadora o, simplemente, a información de carácter cuantitativo.

Es importante mencionar que en el ámbito de las ciencias económicas se suele hacer referencia a los datos en términos de “bienes no rivales”; lo anterior en la medida en que un determinado uso de ellos no excluye otro. Así, por ejemplo, los datos de los usuarios de una red social pueden ser usados para contactar a personas con intereses comunes, para enviar publicidad personalizada o, quizás, para clasificar demográficamente a los usuarios y, sin embargo, tales datos no se agotan.

##### Documento

Según [@Buckland], el término “documento” se emplea normal- mente para referirse a objetos que contienen texto, como cartas, libros, periódicos o escritos. Sin embargo, el autor advierte que el término “texto” bien podría relacionarse con imágenes o sonidos. Todavía más, si se piensa en una tabla de números no resulta para nada forzado pensar en ella como un documento, texto o, incluso, como dato. Así, se resalta el carácter polisémico de las palabras en cuestión, donde una podría estar en lugar de las otras. De modo que, desde el uso de la lengua, es recomendable evitar establecer una demarcación definitiva entre datos, documentos y texto. Aun así, es importante señalar que una buena manera de definir el concepto de documento, y que aplique tanto para fotos o sonidos como para cartas o periódicos, podría ser la siguiente: un conjunto ordenado de datos alineados de acuerdo con un propósito explícito. Cabe agregar que los datos que componen un documento pueden ser, como se mencionó, empleados para un propósito completamente distinto del original.

##### Objeto

Además de datos y documentos, hay otras *cosas* que son informativas, aunque no se suelan ver de esa forma: los objetos. Pongamos por caso un cono de tránsito, que, aunque no se considere *stricto sensu* dato o documento, es información como cosa en la medida en que se presenta como evidencia de un accidente o un vehículo detenido, por ejemplo. [@Buckland] ilustra la noción de objeto informativo al hablar de fósiles y artículos de museos. Ahora bien, la representación que se hace de tales objetos pone de manifiesto su carácter informativo. Así, los artículos de un museo son contados y fotografiados y tal representación constituye, *per se*, nueva información.

##### Eventos

Por su parte, los eventos también se consolidan, desde la perspectiva de [@Buckland], como un tipo de información como cosa. Sin ir más lejos, un experimento puede ser entendido como un evento que sirve como evidencia de la veracidad de una hipótesis determinada. Sin embargo, este tipo de información como cosa está en estrecha relación con la representación. De hecho, Buckland subraya que, en ocasiones, un objeto puede ser considerado información en la medida en que aparece como evidencia de un evento. Esto es claro si se piensa en las huellas de un lobo en la nieve como un objeto informativo, que lo es en la medida en que evidencia el evento que describe el paso de un lobo. Todavía más, muchos de los objetos que se conservan en los museos están allí justamente porque representan algún *evento* de alguna época, como el florero de Llorente, que se conserva en el Museo de la Independencia ubicado en la carrera séptima de Bogotá, Colombia. Aquí es importante señalar que, en ocasiones, la única manera de interactuar con un evento es, justamente, a través de su representación en fotos, videos, narraciones, entre otros.

### Campos de la información

Además de ser polisémico, el término “información” es abordado desde diversas disciplinas, como son la informática, la filosofía, la cognición, la comunicación y las ciencias del lenguaje, la biología, la física, entre otras. Cada disciplina asume diferentes concepciones del término y le da distintos usos. De hecho, [@Garcia] resalta que el concepto posee una extraordinaria generalidad y que lo más conveniente es especificar los sentidos con los que se emplea en ámbitos concretos.

Los distintos modos en los que las diferentes disciplinas asumen el concepto de información se pueden resumir en lo que [@Rendon pp.65] denomina “campos de la realidad en donde se manifiesta un tipo de información específico”, estos son: el *físico*, el *biológico*, el *psicológico* y el *tecnológico*. Vale la pena mencionar que los campos son conceptualizaciones del mundo y por ello son susceptibles de reinterpretaciones o críticas. Sin embargo, como conceptos, son útiles para exponer la historia y los enfoques en torno a la información.

El *campo físico* se enfoca en la dimensión material del mundo y las disciplinas que lo investigan. Aquí, la información existe como un elemento “estrictamente sintáctico” y “en potencia”, sin un significado intrínseco, debido a la ausencia de un intérprete. En el *campo biológico*, la información se presenta en términos de biomoléculas y procesos comunicativos cruciales para la existencia y evolución de los seres vivos. Las teorías genéticas informacionales son ejemplos de enfoques aplicados en este ámbito. En el *campo psicológico*, por su parte, la información adquiere un papel cognitivo y social, donde la inteligencia opera, razona y crea a través de la información. Aquí, tanto las teorías lingüísticas como la antropología abordan la realidad social como un proceso comunicativo en el que la información es un elemento central. Finalmente, el *campo tecnológico* comprende la manipulación de información a través de artefactos u herramientas, destacando la creciente influencia de la tecnología de la información y la comunicación (TIC) en todas las disciplinas y en la sociedad en general.

## Gestión pública

### Gestión

La palabra “gestionar” se define en el diccionario de la Real Academia Española (2001) a partir de tres acepciones: primero, “llevar adelante una iniciativa o un proyecto”; segundo, “ocuparse de la administración, organización y funcionamiento de una empresa, actividad económica u organismo”; y, tercero, “manejar o conducir una situación problemática”.

Estas acepciones mantienen una estrecha relación y podrían, incluso, presentarse de forma conjunta. Así, por gestión se podría entender una cierta iniciativa o proyecto, que tiene que ver con la administración, organización y funcionamiento de un elemento o situación que presenta un carácter problemático. Complementando, [@Munoz pp. 96] expone que tal término “resalta las acciones precisas, oportunas y prácticas en pro de conseguir en el menor tiempo posible, y con la calidad del caso, los propósitos trazados”, asimismo, menciona la autora, la gestión hace parte de las diferentes esferas de vida cotidiana, por lo que cabe hablar de gestión institucional, comunitaria, local, privada, pública, entre otras.

Cada tipo de gestión conlleva sus propios objetivos, que condicionan las acciones que se llevan a cabo para alcanzarlos. En otras palabras, las perspectivas, metas y acciones que fundamentan la gestión en una empresa privada difieren de las de una junta comunitaria. Por un lado, la gestión en una empresa privada tiende a centrarse en la obtención de beneficios en términos generales; mientras que, por otro lado, la gestión en una junta comunitaria se enfoca en identificar los problemas bajo su jurisdicción y en buscar formas de resolverlos. El tipo de gestión que se aborda en lo que sigue es la *gestión pública*.

### Público

La palabra “público” viene del latín *populicus* y está compuesta por *populus* (gente, pueblo) y por el sufijo ---ico (relativo a), es decir, “lo que pertenece al pueblo”. La noción de lo público involucra un elemento social, de comunidad, de relación, de convivencia y, por tanto, de norma. De hecho, “público” aparece también en “república” (*respublica*), la cosa o los asuntos (res---) del pueblo (*publica*). Pues bien, la cuestión de lo público desempeña un papel fundamental en el ámbito de la gestión. Cuando la pregunta por la administración, la organización y el funcionamiento se enfoca en lo que es del ---o para el--- *pueblo*, la gente, todos [^cap_i-5], se espera una manera especial de hacer las cosas, o, al menos, se espera una cierta pregunta por los modos de ser, de actuar.

[^cap_i-5]: Este asunto es cuestionable. Uno de los sentidos que se atribuye al pueblo tiene que ver con la masa, el común de la gente, lo *popular*. Esto quiere decir que hay una sección que no se considera parte de ese pueblo y que, de algún modo, está en una posición privilegiada. Tal concepción no es casualidad. De hecho, la palabra griega *populus* se refería a todos los hombres jóvenes (púber viene de *populus*) y dejaba por fuera a mujeres, niñas, niños y ancianos. Esto pone de manifiesto que la concepción de público y de todos obedece, usualmente, a representaciones y construcciones sociales que varían de acuerdo con la época.

El tema de los modos de ser, o de hacer, se relaciona con la palabra griega *ethos*, ética. La pregunta ética por excelencia, como se plantea en la filosofía griega, adopta la forma de “¿cómo deberíamos vivir?” o “¿qué deberíamos hacer?”. La ética, desde esta perspectiva, involucra la reflexión sobre las “mejores opciones” para el desarrollo de la vida humana, entendida esta como una vida social, en comunidad. Así pues, el ámbito de lo público involucra siempre un aspecto ético.

### Gestión pública

Los significados de las construcciones discursivas que empleamos no se limitan a los significados de las partes que las componen. Así, la noción de “gestión pública” se puede entender, también, como una disciplina que involucra algunos elementos adicionales.

[@Bozeman] presenta una distinción entre dos orígenes de la gestión pública como disciplina. Por un lado, el enfoque B (de *business*), que está más asociado a la administración tradicional y a las disciplinas comerciales. En este enfoque la distinción entre público/privado no resulta tan destacable. Por el otro lado, hay un enfoque P (de *politics*) que considera de vital importancia el análisis de la política pública en el proceso de gestión.

Luego de esta distinción, [@Munoz], siguiendo a [@Bozeman], resalta que la gestión y las políticas públicas son dos caras de la misma moneda. De un lado, la política pública, es decir, una suerte de plan que se ha convenido para atender a una problemática pública. Del otro lado, la puesta en práctica, es decir, la gestión de aquellos planes que se han convenido. Así, la política pública, en cierto sentido, traza unos objetivos que dan cuenta de lo que se debe hacer, mientras que la gestión pública se relaciona más con el método que responde al cómo se va a hacer eso que se piensa realizar. Esta manera de entender el asunto pone de manifiesto la disyuntiva entre teoría y práctica o, si se prefiere, entre el decir y el hacer. Como se sabe, las iniciativas estatales pueden ---o, mejor, suelen--- quedar en el papel. De ahí que la gestión adquiera una importancia considerable.

Es importante mencionar que la concepción de *política pública* suele limitarse al plan, programa o proyecto que genera una administración específica y que tiene un alcance limitado en el tiempo, que usualmente se relaciona con el periodo de gobierno de un determinado personaje o partido político. Sin embargo, la política pública, así como la gestión pública, va más allá de lo coyuntural. Hay acuerdos estatales y sociales para atender a problemas públicos que no están acotados, al menos de manera tan radical, en el tiempo. En este sentido, tanto la política como la gestión pública pueden involucrar procesos transversales que se extienden más allá de los intereses del gobierno de turno.

#### Modelos de gestión pública

Dentro de la mencionada gestión, o puesta en marcha de la política pública, se pueden distinguir modelos. Estos modos de llevar a cabo la política pública no son ajenos a la noción de información. En cada modelo, la importancia concedida a la información va tomando un matiz diferente.

De acuerdo con [@Munoz], se pueden resaltar seis grandes modelos. En primer lugar, el *modelo burocrático*. Este tiene que ver con una organización mecanicista, racionalista y vertical que busca estandarizar los procedimientos y pone al Estado como actor fundamental de la gestión, que puede dar respuesta a todas las problemáticas sociales.

En segundo lugar, el *modelo de la nueva gestión pública*, que, siguiendo a [@Munoz], presenta una noción contractualista, que instala principios gerenciales y empresariales en el sector público donde el ciudadano es visto como cliente. Esa concepción redunda en el desplazamiento del servicio estatal y de la gestión hacia el entorno privado. Además, la noción de ciudadano---cliente se traduce en herramientas de evaluación y medición de los servicios públicos, así como en la gestión por resultados.

En tercer lugar, el modelo de gobernanza, que, de acuerdo con [@Munoz], reconoce que la solución a los problemas públicos no se limita al sector público---estatal o al sector privado, sino a un relacionamiento horizontal entre estos dos últimos y los diferentes actores sociales. Así, este modelo aborda la gestión pública desde una óptica de trabajo colaborativo, donde el Estado debe coordinar y potenciar una red de distintos actores. No obstante, se ha argumentado que esta dinámica puede propiciar la preponderancia de intereses de grupos que cooptan las redes para su beneficio personal.

En cuarto lugar, el *modelo de gobierno abierto*. Para [@Munoz], este se centra en tres principios fundamentales, a saber, transparencia, participación y colaboración. *Transparencia* en cuanto al acceso a la información pública para supervisar el actuar del gobierno; *participación* para propiciar espacios de diálogo y toma de decisiones por parte de la ciudadanía y el sector público; y, finalmente, *colaboración* entre los sectores privado, público y civil para abordar los problemas como una red. Se le denomina gobierno abierto por el énfasis en la *apertura* de datos y procesos para promover la transparencia y facilitar la participación y la colaboración.

En quinto lugar, el *modelo de nuevo servicio público*, que, como señala [@Munoz], retoma las nociones de ciudadanía, un poco descuidadas en la *nueva gestión pública*. Así, tiene como objetivo central el interés público. Se deja de lado el enfoque empresarial para resaltar el *servicio* público. Así, los funcionarios pasan a ser servidores públicos. Se valoran las características particulares y las circunstancias de las personas, no solo su productividad.

Finalmente, en sexto lugar, el *modelo de gestión pública territorial*. Dicho modelo se caracteriza, de acuerdo con [@Munoz], por un enfoque integral que abarca elementos como las relaciones entre Estado, instituciones, sector privado y comunidad. Asimismo, el elemento distintivo tiene que ver con el reconocimiento de la noción de territorio y los modos en que influye en las redes que se establecen entre los diferentes actores sociales. De manera que el propósito central se refiere a la acción común en un territorio determinado.

Ahora bien, los enfoques de gestión pública mencionados se presentan como divisiones teóricas; no obstante, en la práctica, es frecuente encontrarse con modelos híbridos o mezclados. Esta combinación de enfoques hace que la gestión de la información se vuelva más compleja.

## Usos de la información en la gestión pública

Independientemente del modelo o enfoque que la gestión pública adopte, la información desempeña un papel preponderante y transversal. A continuación, se ofrece una perspectiva basada en la experiencia de gestión en la Universidad Nacional de Colombia (UNAL), que describe cuatro principales formas en las que las instituciones hacen uso de la información.

### Uso comunicativo

La información se emplea de manera comunicativa cuando tiene el propósito explícito de transmitir un mensaje a algún receptor que, en muchas ocasiones, puede no ser un individuo en concreto, sino un receptor ideal. Algunos ejemplos de este uso son comunicados oficiales, citaciones, circulares, noticias, boletines informativos, manuales, descripción de funciones, publicaciones en redes sociales, memorandos, correos electrónicos, oficios, entre otros.

Uno de los elementos más sobresalientes del uso comunicativo tiene que ver con dar a conocer lo que las entidades están haciendo. Así, se designan muchos recursos para crear dependencias particulares, contratar especialistas o generar canales específicos para difundir las actividades, los procesos, los objetivos o los logros de una organización. Los motivos de tales esfuerzos pueden ser variados. Por ejemplo, en primer lugar, a través de la difusión de aquello que está realizando ---o que tiene previsto realizar--- una entidad es posible captar la atención de un determinado público que puede contribuir a la visibilidad de la organización y a la construcción de una imagen favorable. En segundo lugar, la difusión de aquello que se realiza en una organización se relaciona con una cierta estrategia de evaluación y vigilancia que permite hacer seguimiento de las entidades. Pero este es ya, como se verá más adelante, otro uso de la información.

Dentro del uso comunicativo, así como en los usos posteriores, hay un elemento ético sobre el que es importante reflexionar. En este caso, podemos hablar del control que suelen hacer algunas organizaciones de las comunicaciones que hacen sus funcionarios, por ejemplo, vigilando los mensajes de los correos electrónicos o restringiendo y monitoreando las páginas a las que acceden los funcionarios desde los equipos vinculados a la organización [^cap_i-6]. Otro elemento destacable dentro del componente ético al respecto del uso comunicativo de la información podría ser el de los correos no deseados, o *spam*.

[^cap_i-6]: Las amenazas a las que se enfrenta una sociedad permeada por la vigilancia son descritas en [@Zuboff].

Finalmente, otro elemento importante dentro del componente ético tiene que ver con la no divulgación de aquella información que puede afectar la imagen de una entidad, aun si tal información hace parte de los procesos de gestión y es de vital importancia darla a conocer para cumplir con los procesos evaluativos y de rendición de cuentas. Todavía más, el encubrimiento de una determinada problemática dentro de los procesos de gestión en una entidad pública no permite alertar a las entidades correspondientes y consolidar un plan de acción que permita abordar desde una perspectiva informada tal problemática y sus efectos. En este sentido, en Colombia se ha consolidado la Ley 1712 de 2014 que pretende regular y fomentar la transparencia y el derecho de acceso a la información pública nacional. No en balde, dentro del discurso habitual de las entidades públicas se suele hacer referencia a la transparencia de datos.

### Uso de registro

Consiste en describir, representar e inventariar hechos, objetos, actividades, individuos o características a través de técnicas de cálculo y registro. Dentro de esta función entran en juego procedimientos como el conteo, la medición, la crónica, entre otros. Algunos ejemplos puntuales de elementos informativos que desempeñen la función de registro son los directorios, los inventarios, los libros de contabilidad, las listas de personal, los planes anuales de vacantes, entre otros. Además, dentro de la función de registro se incluye no solo el objetivo de describir, representar e inventariar, sino también de conservar la información obtenida a través de archivos físicos o digitales y el manejo que se le debe dar a tales archivos.

Por otra parte, este uso no involucra el mero registro sin más. Hay una serie de normas, acuerdos y convenciones que suelen caracterizar los registros de información. Dicho de otro modo, el uso de la información en cuestión está determinado por una suerte de gramática que establece qué características son las que se registran del individuo (por ejemplo, el sexo en lugar del color de los ojos). La gramática no solo establece lo que se registra, sino también cómo se registra. En este sentido, hay una serie de estándares que cada organización establece para unificar sus registros. De hecho, hay una tendencia a establecer unos códigos compartidos a nivel mundial. Un buen ejemplo podría ser el de las normas ISO, que definen estándares internacionales. Pongamos por caso la norma ISO 3166 cuyo propósito es determinar una codificación específica y compartida a nivel internacional para nombrar territorios.

Finalmente, es importante mencionar que en la época actual es común que se registre la mayor cantidad de datos de los usuarios en internet. Así, los sitios web almacenan información sobre la ubicación, el dispositivo desde el cual se accede, el tiempo que el usuario permanece en la página, entre otros datos. Este fenómeno, como es obvio, supone la reflexión ética al respecto de qué debería y qué no debería ser registrado y, por supuesto, de qué se debería y qué no se debería hacer para obtener esos datos. Así, es posible hablar de fenómenos como la violación de la privacidad cuando se accede a datos particulares sin el permiso de los titulares, o cuando se ingresa de manera ilegal a bases de datos que almacenan información de carácter sensible [^cap_i-7].

[^cap_i-7]: En [@Cukier] se aborda la idea de cómo el exceso de datos puede tener impactos significativos en la sociedad.

El uso de registro también supone un problema de carácter ético que tiene que ver con la concepción de la clasificación. En cierto sentido, toda clasificación deja algo por fuera y, al dejarlo, hace ver que eso que se queda por fuera no es. En palabras de Mèlich la clasificación

> ... elimina (por absorción) lo diferente, lo distinto, lo heterogéneo, lo extraño. Las clasificaciones ordenan y rigen a priori formas de comportamiento y de acción. Son performativas, fijan “lo que es” y prescriben “lo que debe ser”. Una lógica ---una ordenación categorial--- posee elementos ontológicos, normativos y formativos. Por eso no hay clasificación alguna que “pueda simplemente ajustarse a los hechos”. [@Melich pp. 30]

Con todo, la clasificación propia del uso de registro que se le da a la información es, quiérase o no, necesaria. A partir de la estandarización se pueden establecer comparaciones y, en general, procedimientos estadísticos que no tendrían cabida si no hubiese normas que permitieran clasificar y agrupar elementos. Podría decirse, pues, con [@Borges pp. 708], que “la imposibilidad de penetrar en el esquema divino del universo no puede, sin embargo, disuadirnos de planear esquemas humanos, aunque nos conste que estos son provisorios”.

### Uso valorativo

Se puede hablar de uso valorativo cuando el objetivo principal de la información es establecer, afirmar o reconocer un determinado juicio sobre algo. Esta función involucra elementos como la evaluación, las metas, los resultados o los incentivos.

El uso valorativo de la información es, sin lugar a dudas, una línea dominante en el ámbito de la información en lo público. Se espera que tanto la ciudadanía como los organismos de control vigilen la gestión de las entidades. Además, la evaluación se consolida como una estrategia que le permite a las entidades determinar si las actividades realizadas efectivamente corresponden a lo que se suponía debía realizarse. De este modo, se pueden establecer planes de acción para corregir cualquier falencia o cambiar las metas y los objetivos.

En este orden de ideas, es posible hablar de dos grandes tipos de evaluación. Por un lado, la evaluación externa, de la que se encargan, usualmente, organizaciones dedicadas a la vigilancia y el control, así como población civil. Por otro lado, la evaluación interna, que se refiere a las estrategias valorativas que aplica la misma entidad, como una auditoría interna.

En la actualidad, el elemento predominante dentro del uso valorativo de la información en el ámbito de lo público es el de los objetivos y los indicadores. Estos se establecen en estrecha relación con las metas de los procesos de gestión y, de acuerdo con el Departamento Administrativo Nacional de Estadística [@DANE_2011], tienen el propósito de describir características, comportamientos o fenómenos de la realidad desde los cuales pueda valorarse el plan, programa o proyecto. En este punto, un elemento de carácter ético que vale la pena considerarse es el de la manipulación de la información con el propósito de mostrar que las metas y los objetivos de los planes, programas o proyectos se alcanzaron de acuerdo con lo previsto, aunque no sea así. Este elemento supone las problemáticas asociadas a la manipulación de datos, que van desde alterar una cifra hasta forzar un dato para que dé cuenta de algo ya decidido de antemano o, incluso, el recalco que se puede hacer de determinadas cifras a través de elementos gráficos, como tablas o barras, incluso colores o figuras, para priorizar información favorable a los procesos evaluativos que se estén llevando a cabo [^cap_i-8].

[^cap_i-8]: [@Huff] da cuenta de cómo se pueden presentar datos de manera engañosa a través de gráficos, lo que puede llevar a interpretaciones cuestionables o manipuladas de la información.

Todavía más, el mero establecimiento de metas y objetivos conlleva un elemento ético. La gestión pública involucra una cierta intervención social, de modo que las metas y los objetivos que siga un plan, programa o proyecto definen y, si se quiere, priorizan las necesidades de una comunidad. Por ejemplo, un proyecto puede tener como objetivo entregar recursos tecnológicos en un territorio puntual, mientras que la población de ese mismo territorio no tiene condiciones suficientes para una alimentación adecuada. Por esto es que, además de la valoración de los procesos de gestión, vale la pena tener en cuenta la valoración a través de estrategias aritméticas básicas como el conteo, que permiten consolidar cifras (p. ej. el número de vinculados a una entidad o el número de personas en condición de vulnerabilidad) que tienen un valor fundamental y pertinente dentro de las diferentes valoraciones de interés para una entidad.

Finalmente, los diferentes usos de la información en la gestión pública pueden estar relacionados. Para este caso, la relación se presenta entre el uso de registro, el uso valorativo y el comunicativo. Es necesario buscar y recopilar información, ya sea a través de procedimientos arit- méticos básicos (como el conteo) o a través de indicadores de gestión, para que la valoración se pueda llevar a cabo. De manera similar, junto con los procesos de evaluación puede haber un interés comunicativo, que se evidencia en el uso de informes para dar a conocer los *resultados* de cualquier etapa del proceso de consolidación y gestión de la información.

### Uso de procesamiento

A partir de un conjunto de operaciones, o procesos, se busca transformar la información existente en nueva información. Con frecuencia, tal transformación persigue el propósito de incidir en la toma de decisiones. De hecho, el procesamiento de información se constituye como una característica interpretativa e interactiva del ser humano con su entorno y con los demás. Así, frente a un elemento informativo, como podría ser el humo, una persona podría llevar a cabo un procesamiento de tal información para advertir un incendio.

Ahora bien, con la incidencia de las TIC, así como con el desarrollo del internet y la importancia concedida a la información en la época actual se han desarrollado técnicas sofisticadas de procesamiento de información como la minería de datos, el procesamiento de lenguaje natural o el *big data*; sin embargo, las actividades aritméticas básicas ya son, de por sí, herramientas de procesamiento de información.

El propósito de este libro no es caracterizar las estrategias de procesamiento de la información, ni argumentar en favor de unas o de otras. No obstante, la tendencia bastante extendida a supervalorar sofisticados algoritmos en detrimento de procesamientos aritméticos básicos puede tener algunas implicaciones que vale la pena considerar: en ocasiones, la tecnología desdibuja la realidad social. Por ejemplo, podría darse una situación en la que los esfuerzos de procesamiento de información estén concentrados en, por decir algo, determinar los campos semánticos de los discursos de los gobernantes de un territorio a través de un sofisticado sistema de procesamiento de lenguaje natural, mientras que, por otra parte, se desconoce el número de personas en situación de vulnerabilidad de ese mismo territorio. Tal número resulta, justamente, del procesamiento a través de técnicas aritméticas básicas y puede ser más oportuno para un programa de intervención que beneficie a la comunidad.

El uso de procesamiento es transversal a los demás usos de la información, pues, constantemente, la información se procesa para generar algún tipo de *comunicación*, para ser *almacenada* y, por supuesto, para llevar a cabo procesos *valorativos*. Un ejemplo de procesamiento de la información puede ser la sistematización y el análisis de datos que hace el [@DANE_2018] del Censo Nacional de Población y Vivienda, donde, *grosso modo*, a partir de la información suministrada de manera individual por cada vivienda censada, se llega a conclusiones de la población nacional [^cap_i-9].

[^cap_i-9]: Conviene resaltar que el proceso de censo de población que adelanta el DANE involucra otros elementos más allá del procesamiento, a saber: especificación de necesidades, diseño, construcción, recolección y acopio, análisis, difusión y evaluación.
