# Conclusiones {.unnumbered}

A lo largo de este libro se exploró cómo el término “información” puede ser empleado en una variedad de contextos, remitiendo a diferentes significados. De hecho, es un término común en las interacciones sociales debido a los avances en telecomunicaciones, computación y el surgimiento del mundo digital. Además, se resaltó que la información puede entenderse como un proceso, como conocimiento y como cosa. Esta última concepción, la de información como cosa, alude a los objetos, procesos, documentos y eventos que pueden servir como evidencia de algo en una situación dada. La información como cosa es manipulable, susceptible de ser procesada, se puede trabajar con ella; por tanto, es sobre la cual se conforman las estadísticas y los indicadores.

También se señaló que la información resulta de bastante utilidad para la gestión pública, entendida esta última como la puesta en marcha de iniciativas, la administración y organización, o el manejo de situaciones problemáticas en el marco de una dimensión social, comunitaria y ética. Asimismo, se destacaron los enfoques de la gestión pública y se subrayó la relación de estos con la información, donde se mencionaron cuatro grandes usos: comunicativo, donde se emplea la información para comunicar mensajes a la comunidad o a un público ideal; de registro, donde se menciona cómo se utiliza la información para describir, representar e inventariar hechos, objetos, actividades y características; valorativo, donde se exploró el uso de la información para establecer juicios sobre el quehacer de las entidades; finalmente, de procesamiento, donde se abordó cómo la información se procesaba para transformarla en nueva información con el propósito de influir en la práctica.

Luego llegó el turno de las cifras estadísticas que, como se sabe, son de gran utilidad para los procesos de gestión, pues proporcionan información necesaria para la toma de decisiones, la evaluación de políticas y la rendición de cuentas. De hecho, el término “estadísticas” proviene de la palabra en latín *statisticus*, que se refiere a lo que es relativo a un Estado. Esta concepción de las estadísticas como una herramienta de conocimiento que permite describir el Estado y los fenómenos de la sociedad resalta su importancia en la gestión pública.
Con el fin de dar cuenta de las estadísticas como objeto de estudio, se describieron algunas características intrínsecas, es decir, necesarias, y otras extrínsecas, es decir, recomendables. Las características intrínsecas señalan que las estadísticas se basan en poblaciones y muestras; hacen uso de variables cualitativas (nominales u ordinales) y cuantitativas (discretas o continuas); implican la agregación de datos a través de conteos o medidas descriptivas de tendencia central, dispersión, localización y simetría; desagregan los datos en subgrupos temporales, geográficos y temáticos; se representan de manera gráfica y tabular para facilitar su visualización; y, por último, requieren de mecanismos de divulgación y comunicación que permitan darlas a conocer.

Las características extrínsecas, por su parte, advierten de la importancia de ser incluyentes, de tener en cuenta la diversidad de poblaciones y velar por que todas las personas tengan acceso a la información estadística; de ser comparables a nivel institucional, nacional e internacional; de cumplir con las leyes institucionales, estatales o internacionales, así como de tener en cuenta cuestiones éticas; de procurar que la información estadística sea pública, transparente y abierta; de hacer uso intensivo de las TIC; de describir los datos a través de metadatos para reducir malentendidos o tergiversaciones; y, por último, de la importancia de conformar estadísticas a través de un proceso estadístico que abarque diversas fases, desde la detección de necesidades hasta la evaluación.

Después de las estadísticas, el presente libro se centró en los indicadores. Se mostró cómo, desde una perspectiva etimológica, el término “indicador” alude a señalar o mostrar algo. Se explicó cómo, en la práctica, los indicadores se utilizan para focalizar, medir y describir fenómenos. Asimismo, se abordó la dificultad de precisar una tipología para los indicadores y se discutió, entre otras, la tipología de indicadores cuantitativos y cualitativos, donde los primeros se basan en mediciones numéricas, mientras que los segundos se centran en características no numéricas, como percepciones y actitudes. Además, se abordó la tipología de indicadores temáticos, que desempeñan un papel esencial en la medición y evaluación de diversas dimensiones de interés en la sociedad, como la economía, la salud, la educación, el medio ambiente y la demografía, mientras permiten la comparación y el contraste entre diferentes países, regiones e instituciones, lo que resulta valioso en el ámbito de la toma de decisiones a nivel estatal e institucional.

Después de los indicadores temáticos, se abordó la tipología de indicadores de gestión. Estos siguen una lógica de procesos que pueden ser recurrentes, es decir, que no están acotados en el tiempo, y no recurrentes, que están acotados en el tiempo. Además, los procesos siguen una lógica de estructura de cadena de valor, es decir, en su interior se agrupan en varias tipologías que involucran insumos, actividades, productos y resultados.

En el libro también se destacó cómo a la base de los indicadores hay una naturaleza matemática, es decir que, sin importar su tipología (cuantitativos, temáticos, de gestión o jerarquía), se basan en operaciones matemáticas, que pueden ser simples o complejas. En este contexto, las medidas estadísticas, como las medidas de tendencia central, dispersión, localización y forma, se utilizan para comprender la distribución y las características de los datos; las frecuencias, tanto absolutas como relativas, proporcionan información sobre la cantidad de veces que ocurrió un fenómeno en una población o muestra; las razones permiten comparar cantidades provenientes de diferentes poblaciones o muestras, o diferentes subconjuntos de una misma población o muestra; las tasas, por otro lado, son relaciones que incluyen el factor tiempo, y se aplican en diversos campos, como la demografía y la economía; los índices, por su parte, son indicadores más complejos que a menudo se utilizan para medir fenómenos complejos y multidimensionales, como la calidad de vida.

Ya hacia el final del libro se presentó el denominado Modelo P2C-T, que se enfoca en la conformación de estadísticas e indicadores, así como en la creación de áreas de estadística o analítica de datos dentro de instituciones. Este modelo surge de la experiencia institucional de gestión en la UNAL y consta de cinco dimensiones: planeación estadística (P), conceptualización y metodologías (C), producción estadística (P), disposición y gestión de herramientas tecnológicas (T), y cultura estadística (C). Además, se destacan tres soportes necesarios para que el modelo funcione: apoyo institucional, acceso y disposición del talento humano, y acceso a recursos financieros.

Como hemos visto hasta ahora, el presente libro proporciona a los lectores herramientas para mejorar la calidad de la gestión pública a través de la reflexión de los conceptos que hay a la base de la conformación de cifras estadísticas e indicadores. Asimismo, destaca cómo una gestión informada y basada en datos, que tenga en cuenta las precisiones teóricas de los conceptos que la componen, puede conducir a mejores procesos, como la toma de decisiones o el seguimiento más preciso de los resultados, que, en última instancia, beneficia a los Estados, sus instituciones y a las comunidades y la sociedad en general.

A continuación, se presentan algunas conclusiones específicas que resultan de este proceso de investigación. En primer lugar, se destaca que la información desempeña un papel fundamental en la conformación de estadísticas e indicadores. Esta concepción se caracteriza por su enfoque cuantitativo y estructurado. No obstante, se abre un espacio para la exploración de cómo otros modos de entender la información, por ejemplo, como conocimiento o como información cualitativa no estructurada, podrían influir en la producción de estadísticas e indicadores, así como en su gestión en el ámbito público.

En segundo lugar, las estadísticas se presentan como una herramienta esencial para la representación y comprensión de los acontecimientos significativos de un Estado. Sin embargo, rara vez se las aborda como un objeto de estudio en el ámbito de la gestión pública. En su lugar, se suelen establecer planes y directrices para la recopilación de datos estadísticos. No obstante, es útil y necesario caracterizar las estadísticas como una entidad independiente.

En tercer lugar, cuando se habla de indicadores es común que su comprensión se limite a los indicadores de gestión, aunque en realidad son considerablemente más diversos. Es esencial comprender y utilizar una variedad de indicadores de manera adecuada en la gestión pública. Además, es importante destacar la utilidad de distinguir entre indicadores y estadísticas, a pesar de que esto no siempre se haga.

En cuarto lugar, el modelo P2C-T se revela como un recurso valioso que refleja la experiencia de la UNAL el cual, aunque se basa en las directrices establecidas a nivel estatal, permite concluir que ningún modelo o propuesta es definitivo, y la capacidad de adaptar y afinar las directrices a las necesidades específicas de una entidad se considera un ejercicio apreciable.

Ahora bien, este libro no solo proporciona un valioso apoyo para quienes trabajan en la gestión pública, sino también involucra cuestiones sociales subyacentes. En ocasiones, el proceso de investigación adelantado en este documento se concentró, por ejemplo, en reflexiones al respecto de las implicaciones éticas asociadas a la clasificación de poblaciones, inherente a cualquier proceso de generación de datos estadísticos, o en el carácter polisémico de los conceptos relacionados con las estadísticas e indicadores en la gestión pública. De esto se concluye que la temática abordada a lo largo de estas páginas fomenta ---e, incluso, exige--- la discusión y la reflexión. Por lo tanto, resulta interesante y útil explorar la comprensión de términos como información, gestión, público, estadísticas e indicadores a la luz de varios enfoques y áreas del conocimiento.


