# Introducción {.unnumbered}

Las preguntas sobre los modos en que se gestiona la información dentro de las entidades no son un tema menor. Para quienes están involucrados en este ámbito, pueden resultar interesantes ---o, sobre todo, frecuentes--- cuestionamientos acerca de cómo recopilar, analizar y emplear datos para respaldar el funcionamiento interno de las instituciones. Sin embargo, al abordar estos interrogantes, es frecuente encontrarse con el desafío de definir y comprender plenamente ciertos componentes que conforman el ámbito de la gestión. ¿Hasta qué punto es precisa la comprensión al aludir a conceptos como información, estadísticas o indicadores? ¿Hasta qué punto se comparte una visión clara de cómo estas piezas se integran de manera efectiva en la práctica?

En este escenario, este libro se presenta con el propósito de proporcionar apoyo conceptual a las entidades públicas en el estudio y la construcción de estadísticas e indicadores institucionales, claves para los procesos de gestión. Para lograr este objetivo, el libro se estructura en cuatro capítulos descritos a continuación.

En el primer capítulo se subraya la importancia de la información en entornos altamente tecnológicos y digitalizados, mientras se da cuenda del término "información" como un elemento polisémico que puede ser abordado desde una perspectiva etimológica y pragmática, donde se resalta la noción de información como cosa, que es susceptible de ser manipulada, analizada y procesada. Asimismo, se resalta la relación entre la gestión pública ---que implica la formulación y ejecución de estrategias destinadas a asuntos de interés público--- y la información, y se destacan tres usos fundamentales de la información en tal contexto: comunicativo, de registro y valorativo.

El segundo capítulo se centra en el análisis de las estadísticas, las cuales se definen como un conjunto de datos organizados en cifras descriptivas que desempeñan un papel fundamental en la representación y la comprensión de la realidad social, especialmente en el contexto de la gestión pública. La finalidad de este capítulo es explorar las características de las estadísticas como un objeto de estudio, a partir de dos categorías: características intrínsecas y características extrínsecas. Las primeras se enfocan en identificar las condiciones que deben cumplirse para hablar propiamente de estadísticas. Las segundas, por su parte, se relacionan con las recomendaciones pertinentes para el uso de las estadísticas en el ámbito de la gestión pública. Ahora bien, es importante destacar que este capítulo no pretende formular directrices específicas ni establecer un modelo concreto para la recopilación y consolidación de cifras estadísticas, sino describirlas como objeto de análisis.

El tercer capítulo aborda el concepto de “indicadores” como herramientas fundamentales en la medición y evaluación de fenómenos de interés en el ámbito público. En este sentido, se desglosan las funciones primordiales que los indicadores desempeñan en dicho contexto. El capítulo avanza explorando la relación entre las cifras estadísticas y los indicadores, resaltando sus aplicaciones prácticas. Además, se introduce una tipología de indicadores que abarca diversas categorías, con énfasis en la importancia de comprenderlas y utilizarlas de manera conjunta para lograr una gestión efectiva en el ámbito público. Finalmente, se pone de manifiesto la base matemática que subyace en la formulación de indicadores, junto con la exposición de diversas estrategias, como medidas estadísticas, frecuencias, razones, tasas e índices, que se emplean en su desarrollo.

En el cuarto capítulo se presentan algunos elementos y recomendaciones prácticas que buscan dar cuenta del proceso de creación de estadísticas e indicadores, así como la implementación de áreas de estadística o análisis de datos dentro de la Universidad Nacional de Colombia. Con este propósito en mente, se introduce un modelo propio denominado Modelo P2C-T, que se compone de cinco dimensiones clave: planeación estadística (P), conceptualización y metodologías (C), producción estadística (P), gestión de herramientas tecnológicas (T) y promoción de una cultura estadística (C), y tres pilares fundamentales que se deben tener en cuenta para que el modelo funcione de manera efectiva: 1) el respaldo institucional, 2) la disponibilidad de talento humano capacitado y 3) el acceso a recursos financieros. El propósito de este capítulo no es proponer una metodología específica que deba ser adoptada por todas las instituciones, sino, más bien, dar a conocer una experiencia particular que pueda servir de apoyo.


