# Presentación {.unnumbered}

Cuando se trata de las instituciones, lo humano subyace en el fondo del concepto de organización. La organización está compuesta por la estrategia, los sistemas, los procesos, la estructura, las personas, los valores, las habilidades o capacidades y los estilos de trabajo [^presentacion-1] . Todos y cada uno de estos elementos concurren para el éxito de las instituciones en el logro de sus fines.

[^presentacion-1]: Es el modelo de las 7S de Mckinsey. ["MODELO DE LAS 7'S de McKINSEY" LECTURA COMPLEMENTARIA Nº 2](https://www.academia.edu/42963084/_%20MODELO_DE_LAS_7S_de_McKINSEY_LECTURA_COMPLEMENTARIA%20_No_2){target="_blank"}

En el diseño estratégico se plasma el ADN de la organización, la misión, la visión, los grandes propósitos y las maneras como se ha de concretar el quehacer de la institución. La eficiencia, la eficacia, la efec- tividad se juzgan fundamentalmente a la luz de la estrategia.

Con frecuencia se piensa que solo comprendiendo el organigrama se logran identificar las coordenadas del lugar que cada individuo ocupa en la institución, y que solo basta con leer el manual de funciones para saber qué hacer todos los días ante contextos a veces inerciales y en ocasiones inesperados. En realidad, en los procesos de inducción y capacitación de los trabajadores se pasa por alto el hecho de que la estructura está determinada por la estrategia, los sistemas [^presentacion-2] que componen la organización y los procesos que se requieren para materializar el objeto social de la institución; de hecho, aunque no parezca, en la gestión pública en países como el nuestro muchos de los procesos, las actividades y las funciones se incorporan basados en los niveles de desconfianza prevalecientes en la organización.

[^presentacion-2]: Se usa la palabra sistemas en un sentido amplio, no se refiere a la tecnología.

Las coordenadas de ubicación del individuo o de un colegiado son multidimensionales, se puede pertenecer a varios sistemas a la vez actuando desde las intersecciones o en el resultado de una unión de dichos sistemas, estar adscrito a diversos procesos sincrónicos o asincrónicos y contribuir al logro de solo una parte de los objetivos misionales que constituyen el todo. En realidad, la red de creación de valor de una institución poco tiene de lineal, es multidimensional. Entender esa múltiple afiliación de las personas es clave para hacer consciente el rol esencial que todo individuo tiene en relación con las responsabilidades que le corresponden como parte de la red de valor de la información; red que abarca desde el surgimiento de un dato clave hasta el uso que la organización haga de la información, las estadísticas e indicadores para comprender a la entidad en su conjunto y tomar las mejores decisiones.

Como se verá a lo largo de este libro, los datos, las estadísticas, los indicadores, la información tienen que emerger de los procesos cotidianos de la organización como algo natural, no pueden ser considerados una carga cuando se comprende la importancia de la calidad y oportunidad de la información.

Los individuos y colegiados son, a la vez, proveedores y usuarios, atienden varios procesos, se articulan en diversos sistemas y, para poder sobrevivir con éxito en medio de tanta complejidad, se requieren liderazgos efectivos que garanticen sincronía y armonía. Para lograrlo es necesario, además de liderazgo distribuido, es decir, colectivo, conciencia de la ubicación, nitidez en los roles y las funciones, y normalización.

La normalización parte de unificar el lenguaje y los significados, precisar los metadatos, decidir el día y la hora de las emisiones y recepciones, unas reglas claras de lo que significa el carácter oficial de la información y, pensando en la estructura, ahora sí en el organigrama, comprender y valorar lo que se entenderá por los canales oficiales por los que ha de fluir la información y el adecuado uso que debe hacerse de las jerarquías que están detrás del organigrama. En la normalización se debe dejar establecido qué hacer cuando las contingencias e imprevistos emergen, por ejemplo, ante una catástrofe o una pandemia, momentos en los cuales todas las variables y tendencias "se desordenan".

Aquí es donde aparece la importancia de las otras dimensiones de la organización: las personas, los valores, las habilidades y los estilos de trabajo. Las jerarquías se ejercen con la autoridad que surge de los conocimientos, las experiencias y los estilos de liderazgo de los jefes para que logren sincronizar y armonizar al todo y a sus partes. La integridad es constitutiva de ese liderazgo.

Las personas que ejercen sus roles y sus capacidades contribuyen al grupo también con sus conocimientos, experiencias, estilos de aprendizaje, disposición al trabajo en equipo, habilidades de liderazgo y comunicación, y disposición a acatar los ritos y las normas de la organización. Los estilos de trabajo, las prácticas, se van estructurando y, a veces, fosilizando con las vivencias de todos los días, entran al subconsciente de las personas y de la organización y difícilmente son percibidas mediante procesos de metacognición a los cuales estamos poco acostumbrados. Se requiere que con frecuencia alguien externo, los denominados "pares", las evalúe y las critique desde el balcón.

Por tratarse del mundo de los humanos es necesario tener en cuenta que en las organizaciones operan los organigramas, pero que con frecuencia ---y a veces por fortuna--- conviven otras formas de organización: las informales, las relaciones verdaderas, la de las amistades, las redes, los encuentros en los corredores o las citas virtuales y por allí, desde la clandestinidad, fluye también una valiosa información. El rumor lleva estadísticas, indicadores, información, allí se despliegan a plenitud los modelos mentales, los imaginarios, el juicio despiadado y cruel que se hace sobre los líderes o sobre las partes centrales de los organigramas, que concentran el poder y los recursos. Es la "picota pública" de los pa- sillos. Sería maravilloso poder documentar y volver información valiosa, ojalá con indicadores cualitativos, lo que sucede en ese mundo real pero incomprensible de los rumores.

Quería con estas pocas notas hacer evidente la complejidad de este mundo de las estadísticas y los indicadores para que realmente funcionen con efectividad. Los obstáculos saltan a la vista y adoptan diversos matices y lenguajes: "que esta organización es tan compleja que no puede simplificarse como lo pretenden los estadísticos"; "que esta institución es única en el planeta tierra y que por tanto no tiene referentes para hacer comparaciones y determinar umbrales y rangos"; "que es un esfuerzo vano establecer retos o metas basándose en los *rankings* nacionales o internacionales por que hacemos cosas que ninguna otra entidad hace"; "somos muy pocos y tan mal pagados que no es razonable que nos evalúen, juzguen y nos exijan más"; "es absurdo que los estadísticos importen modelos desde lo privado pretendiendo que nuestra entidad se comporte como empresa".

Somos conscientes de la dificultad de mirarse al espejo con detalle para lograr percibir nuestras fortalezas y debilidades. Las estadísticas y los indicadores, con las verdades crueles que ellos transportan, con los mensajes profundos que contienen para describir lo que somos, lo que fuimos y lo que seremos (si se mantienen las cosas como van), nos van dando pistas acerca de cómo proceder para salir de la zona de confort y entrar al mundo de la innovación y el cambio.

Ahora sí, bienvenidos a los contenidos profundos de los capítulos de este libro, es un gustoso e interesante tratado de la estadística aplicable a lo público; pero, nunca pierden de vista la dimensión humana que está detrás de cada párrafo, de cada algoritmo, de cada variable, y el esfuerzo adicional que se requiere para que toda la organización opere con sincronía y armonía sin perder el horizonte estratégico de los fines misionales.

> Carlos Alberto Garzón Gaitán \
Profesor Emérito, Universidad Nacional de Colombia \
Octubre 11 de 2023
